name: Deploy ZIP to GitHub Pages
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Find ZIP in repo root
        run: |
          ZIPFILE=$(ls *.zip 2>/dev/null | head -n1)
          if [ -z "$ZIPFILE" ]; then
            echo "No .zip found in repo root"; exit 1
          fi
          echo "ZIPFILE=$ZIPFILE" >> $GITHUB_ENV
          echo "Found: $ZIPFILE"

      - name: Unzip
        run: |
          rm -rf site out
          mkdir site
          unzip -q "$ZIPFILE" -d site

      - name: Show folder tree (debug)
        run: |
          sudo apt-get update >/dev/null 2>&1 || true
          sudo apt-get install -y tree >/dev/null 2>&1 || true
          echo "=== TREE site (3 levels) ==="
          tree -a -L 3 site || (echo "tree not available"; ls -laR site | head -n 500)

      - name: Try to find package.json (any depth)
        id: findpkg
        run: |
          PKG_PATH=$(find site -maxdepth 4 -name package.json -not -path "*/node_modules/*" | head -n1 || true)
          if [ -n "$PKG_PATH" ]; then
            APP_DIR=$(dirname "$PKG_PATH")
            echo "APP_DIR=$APP_DIR" >> $GITHUB_ENV
            echo "Found package.json in: $APP_DIR"
          else
            echo "No package.json found — will deploy static files."
          fi

      - name: Setup Node (only if package.json found)
        if: env.APP_DIR
        uses: actions/setup-node@v4
        with:
          node-version
